import os

SESSION_REDIS_HOST = os.environ.get("REDIS_HOST")
SESSION_REDIS_PORT = os.environ.get("REDIS_PORT")
SESSION_REDIS_SOCKET_TIMEOUT = 0.1
SESSION_REDIS_DB = 3
SESSION_REDIS_RETRY_ON_TIMEOUT = False
SESSION_REDIS_PREFIX = ''